global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3000']
    scrape_interval: 30s
    metrics_path: /health

  - job_name: 'loyalty-service'
    static_configs:
      - targets: ['loyalty-service:3000']
    scrape_interval: 30s
    metrics_path: /health

  - job_name: 'campaign-service'
    static_configs:
      - targets: ['campaign-service:3000']
    scrape_interval: 30s
    metrics_path: /health

  - job_name: 'survey-service'
    static_configs:
      - targets: ['survey-service:3000']
    scrape_interval: 30s
    metrics_path: /health

  - job_name: 'coupon-service'
    static_configs:
      - targets: ['coupon-service:3000']
    scrape_interval: 30s
    metrics_path: /health

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3000']
    scrape_interval: 30s
    metrics_path: /health

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3000']
    scrape_interval: 30s
    metrics_path: /health

  - job_name: 'integration-service'
    static_configs:
      - targets: ['integration-service:3000']
    scrape_interval: 30s
    metrics_path: /health